# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop src

test:
	OCAMLRUNPARAM=b dune exec test/main.exe

check:
	@bash check.sh

finalcheck:
	@bash check.sh final

zip:
	rm -f battleship.zip
	zip -r battleship.zip . -x@exclude.lst

clean:
	dune clean
	rm -f battleship.zip

doc:
	dune build @doc
	@bash opendoc.sh

opendoc: doc
	@bash opendoc.sh

game: 
	dune build
	dune exec bin/main.exe